import { TaskStatus } from "./interfaces";

export const DUMMY_DATA = [
    { id: 1, title: "Complete Project Proposal", description: "Draft and finalize the project proposal.", status: TaskStatus.PENDING, dueDate: new Date("2025-02-20") },
    { id: 2, title: "Team Meeting", description: "Weekly team meeting to discuss progress.", status: TaskStatus.IN_PROGRESS, dueDate: new Date("2025-02-18") },
    { id: 3, title: "Fix Bug #123", description: "Resolve login issue reported by QA.", status: TaskStatus.COMPLETED, dueDate: new Date("2025-02-14") },
    { id: 4, title: "Design Review", description: "Review UI/UX changes with the design team.", status: TaskStatus.PENDING, dueDate: new Date("2025-02-22") },
    { id: 5, title: "Write Documentation", description: "Complete API documentation for the backend services.", status: TaskStatus.IN_PROGRESS, dueDate: new Date("2025-02-25") },
    { id: 6, title: "Database Optimization", description: "Optimize queries for better performance.", status: TaskStatus.COMPLETED, dueDate: new Date("2025-02-12") },
    { id: 7, title: "Prepare Sprint Report", description: "Summarize progress for the sprint review.", status: TaskStatus.PENDING, dueDate: new Date("2025-02-28") },
    { id: 8, title: "Deploy New Release", description: "Deploy the latest release to production.", status: TaskStatus.IN_PROGRESS, dueDate: new Date("2025-02-19") },
    { id: 9, title: "Write Test Cases", description: "Add missing unit tests for critical modules.", status: TaskStatus.COMPLETED, dueDate: new Date("2025-02-15") },
    { id: 10, title: "Client Demo", description: "Prepare and conduct a client demo session.", status: TaskStatus.PENDING, dueDate: new Date("2025-03-01") },
    { id: 11, title: "Code Review", description: "Review PRs from the development team.", status: TaskStatus.IN_PROGRESS, dueDate: new Date("2025-02-20") },
    { id: 12, title: "Security Audit", description: "Conduct a security audit for the application.", status: TaskStatus.COMPLETED, dueDate: new Date("2025-02-10") },
    { id: 13, title: "Feature Planning", description: "Plan features for the upcoming release.", status: TaskStatus.PENDING, dueDate: new Date("2025-02-27") },
    { id: 14, title: "Frontend Refactoring", description: "Improve component structure in React app.", status: TaskStatus.IN_PROGRESS, dueDate: new Date("2025-02-23") },
    { id: 15, title: "Update Dependencies", description: "Update all outdated npm dependencies.", status: TaskStatus.COMPLETED, dueDate: new Date("2025-02-16") },
    { id: 16, title: "Interview Candidate", description: "Conduct interview for frontend developer role.", status: TaskStatus.PENDING, dueDate: new Date("2025-02-21") },
    { id: 17, title: "Product Strategy Meeting", description: "Discuss the roadmap with stakeholders.", status: TaskStatus.IN_PROGRESS, dueDate: new Date("2025-02-24") },
    { id: 18, title: "Refactor Backend Code", description: "Improve maintainability of backend services.", status: TaskStatus.COMPLETED, dueDate: new Date("2025-02-13") },
    { id: 19, title: "User Feedback Analysis", description: "Analyze feedback from recent user surveys.", status: TaskStatus.PENDING, dueDate: new Date("2025-03-03") },
    { id: 20, title: "Performance Testing", description: "Perform load testing on API endpoints.", status: TaskStatus.IN_PROGRESS, dueDate: new Date("2025-02-22") },
    { id: 21, title: "Write Blog Post", description: "Write a technical blog about React best practices.Write a technical blog about React best practices.Write a technical blog about React best practices.", status: TaskStatus.COMPLETED, dueDate: new Date("2025-02-11") },
    { id: 22, title: "QA Testing", description: "Ensure all features pass QA testing.", status: TaskStatus.PENDING, dueDate: new Date("2025-02-26") },
    { id: 23, title: "Optimize Images", description: "Reduce size of assets for better performance.", status: TaskStatus.IN_PROGRESS, dueDate: new Date("2025-02-17") },
    { id: 24, title: "Fix UI Glitches", description: "Resolve minor UI issues reported by users.", status: TaskStatus.COMPLETED, dueDate: new Date("2025-02-15") },
    { id: 25, title: "Automate Deployment", description: "Set up CI/CD pipeline for auto-deployment.", status: TaskStatus.PENDING, dueDate: new Date("2025-02-29") },
    { id: 26, title: "Customer Support Training", description: "Train support team on handling new features.", status: TaskStatus.IN_PROGRESS, dueDate: new Date("2025-02-20") },
    { id: 27, title: "Add Dark Mode", description: "Implement dark mode in the application.", status: TaskStatus.COMPLETED, dueDate: new Date("2025-02-18") },
    { id: 28, title: "Backend API Cleanup", description: "Remove unused endpoints and refactor.", status: TaskStatus.PENDING, dueDate: new Date("2025-02-25") },
    { id: 29, title: "Conduct User Interviews", description: "Get feedback from power users.", status: TaskStatus.IN_PROGRESS, dueDate: new Date("2025-02-19") },
    { id: 30, title: "Update README", description: "Revise project documentation for contributors.", status: TaskStatus.COMPLETED, dueDate: new Date("2025-02-14") },
];